# -*- coding: utf-8 -*-
"""problem 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SbtL5cob5nSiD9BBocOpynzcmuF5uAls
"""

import numpy as np

def distinct_words(corpus):
    return list(set(corpus))

corpus = ["Virat", "Kohli", "is", "the", "greatest", "batsman", "of", "this", "generation"]

# Call distinct_words to get the list of distinct words
words = distinct_words(corpus)

# Call co_occurrence_matrix to get the co-occurrence matrix
co_matrix, words = co_occurrence_matrix(corpus)

# Print the co-occurrence matrix and words
print("Co-occurrence Matrix:")
print(co_matrix)
print("\nDistinct Words:")
print(words)