# -*- coding: utf-8 -*-
"""problem 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GyKDpJXK-4iFjlGeYbmhiCTASemtqXFf
"""

import numpy as np

# Assuming you have already defined distinct_words and co_occurrence_matrix functions
from sklearn.decomposition import PCA

corpus = ["Virat", "Kohli", "is", "the", "greatest", "batsman", "of", "this", "generation"]

# Get the co-occurrence matrix
co_matrix, words = co_occurrence_matrix(corpus)

# Perform dimensionality reduction using PCA
embeddings = dimensionality_reduction(co_matrix, k=2)

# Assuming you have already defined the plot_2d_vectors function
# Call the function to plot the 2D vectors
plot_2d_vectors(embeddings, words)