# -*- coding: utf-8 -*-
"""problem 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uDmc63u9_ibwo9rEoe78Mo2UG3zQcTVn
"""

corpus = ["Virat", "Kohli", "is", "the", "greatest", "batsman", "of", "this", "generation"]
distinct_words_list = distinct_words(corpus)
print(distinct_words_list)